name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Create virtualenv
        run: python3 -m venv venv
      - uses: actions/cache@v3
        with:
          path: venv/
          key: ${{ runner.os }}-${{ matrix.python }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Use virtualenv
        run: source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Static type checking
        run: make type
      - name: Lint
        run: make lint
      - name: Formatting
        run: make format-check
      - name: Unit tests
        run: make test
      - name: Django Static Checks
        run: make check